import { PlantType } from './types';

export const METAL_PROPERTIES: Record<string, { potential: number; atomicWeight: number; baseColor: string; lsprRange: string; group: string }> = {
  'Hydrogen': { potential: 0.00, atomicWeight: 1.008, baseColor: '#f8fafc', lsprRange: 'Clear', group: 'Non-metal' },
  'Helium': { potential: 0, atomicWeight: 4.0026, baseColor: '#f8fafc', lsprRange: 'Clear', group: 'Noble Gas' },
  'Lithium': { potential: -3.04, atomicWeight: 6.94, baseColor: '#cbd5e1', lsprRange: 'None', group: 'Alkali Metal' },
  'Beryllium': { potential: -1.85, atomicWeight: 9.0122, baseColor: '#94a3b8', lsprRange: 'None', group: 'Alkali Earth' },
  'Boron': { potential: -0.87, atomicWeight: 10.81, baseColor: '#78350f', lsprRange: 'None', group: 'Metalloid' },
  'Carbon': { potential: 0.13, atomicWeight: 12.011, baseColor: '#1e293b', lsprRange: 'None', group: 'Non-metal' },
  'Titanium': { potential: -1.63, atomicWeight: 47.867, baseColor: '#475569', lsprRange: 'None', group: 'Transition' },
  'Chromium': { potential: -0.74, atomicWeight: 51.996, baseColor: '#64748b', lsprRange: 'None', group: 'Transition' },
  'Manganese': { potential: -1.18, atomicWeight: 54.938, baseColor: '#64748b', lsprRange: 'None', group: 'Transition' },
  'Iron': { potential: -0.44, atomicWeight: 55.845, baseColor: '#451a03', lsprRange: 'Black/Brown', group: 'Transition' },
  'Cobalt': { potential: -0.28, atomicWeight: 58.933, baseColor: '#1e1b4b', lsprRange: 'None', group: 'Transition' },
  'Nickel': { potential: -0.25, atomicWeight: 58.693, baseColor: '#475569', lsprRange: 'None', group: 'Transition' },
  'Copper': { potential: 0.34, atomicWeight: 63.546, baseColor: '#9a3412', lsprRange: 'Orange/Red', group: 'Transition' },
  'Zinc': { potential: -0.76, atomicWeight: 65.38, baseColor: '#f8fafc', lsprRange: 'White/Clear', group: 'Post-transition' },
  'Silver': { potential: 0.80, atomicWeight: 107.87, baseColor: '#78350f', lsprRange: 'Yellow/Brown', group: 'Transition' },
  'Cadmium': { potential: -0.40, atomicWeight: 112.41, baseColor: '#f8fafc', lsprRange: 'None', group: 'Post-transition' },
  'Tin': { potential: -0.14, atomicWeight: 118.71, baseColor: '#94a3b8', lsprRange: 'None', group: 'Post-transition' },
  'Lead': { potential: -0.13, atomicWeight: 207.2, baseColor: '#334155', lsprRange: 'None', group: 'Post-transition' },
  'Platinum': { potential: 1.18, atomicWeight: 195.08, baseColor: '#1e293b', lsprRange: 'Black/Grey', group: 'Transition' },
  'Gold': { potential: 1.50, atomicWeight: 196.97, baseColor: '#991b1b', lsprRange: 'Purple/Ruby', group: 'Transition' },
  'Mercury': { potential: 0.85, atomicWeight: 200.59, baseColor: '#e2e8f0', lsprRange: 'Clear', group: 'Post-transition' },
  'Palladium': { potential: 0.95, atomicWeight: 106.42, baseColor: '#334155', lsprRange: 'Black/Dark Grey', group: 'Transition' },
  'Sodium': { potential: -2.71, atomicWeight: 22.990, baseColor: '#cbd5e1', lsprRange: 'None', group: 'Alkali Metal' },
  'Magnesium': { potential: -2.37, atomicWeight: 24.305, baseColor: '#cbd5e1', lsprRange: 'None', group: 'Alkali Earth' },
  'Aluminum': { potential: -1.66, atomicWeight: 26.982, baseColor: '#cbd5e1', lsprRange: 'None', group: 'Post-transition' },
  'Potassium': { potential: -2.93, atomicWeight: 39.098, baseColor: '#cbd5e1', lsprRange: 'None', group: 'Alkali Metal' },
  'Calcium': { potential: -2.87, atomicWeight: 40.078, baseColor: '#cbd5e1', lsprRange: 'None', group: 'Alkali Earth' },
};

// Complete 118 Element Dataset for Periodic Table
export const ALL_ELEMENTS = [
  // Row 1
  { n: 1, s: 'H', m: 'Hydrogen', g: 'Non-metal', x: 1, y: 1 },
  { n: 2, s: 'He', m: 'Helium', g: 'Noble Gas', x: 18, y: 1 },
  // Row 2
  { n: 3, s: 'Li', m: 'Lithium', g: 'Alkali Metal', x: 1, y: 2 },
  { n: 4, s: 'Be', m: 'Beryllium', g: 'Alkali Earth', x: 2, y: 2 },
  { n: 5, s: 'B', m: 'Boron', g: 'Metalloid', x: 13, y: 2 },
  { n: 6, s: 'C', m: 'Carbon', g: 'Non-metal', x: 14, y: 2 },
  { n: 7, s: 'N', m: 'Nitrogen', g: 'Non-metal', x: 15, y: 2 },
  { n: 8, s: 'O', m: 'Oxygen', g: 'Non-metal', x: 16, y: 2 },
  { n: 9, s: 'F', m: 'Fluorine', g: 'Halogen', x: 17, y: 2 },
  { n: 10, s: 'Ne', m: 'Neon', g: 'Noble Gas', x: 18, y: 2 },
  // Row 3
  { n: 11, s: 'Na', m: 'Sodium', g: 'Alkali Metal', x: 1, y: 3 },
  { n: 12, s: 'Mg', m: 'Magnesium', g: 'Alkali Earth', x: 2, y: 3 },
  { n: 13, s: 'Al', m: 'Aluminum', g: 'Post-transition', x: 13, y: 3 },
  { n: 14, s: 'Si', m: 'Silicon', g: 'Metalloid', x: 14, y: 3 },
  { n: 15, s: 'P', m: 'Phosphorus', g: 'Non-metal', x: 15, y: 3 },
  { n: 16, s: 'S', m: 'Sulfur', g: 'Non-metal', x: 16, y: 3 },
  { n: 17, s: 'Cl', m: 'Chlorine', g: 'Halogen', x: 17, y: 3 },
  { n: 18, s: 'Ar', m: 'Argon', g: 'Noble Gas', x: 18, y: 3 },
  // Row 4
  { n: 19, s: 'K', m: 'Potassium', g: 'Alkali Metal', x: 1, y: 4 },
  { n: 20, s: 'Ca', m: 'Calcium', g: 'Alkali Earth', x: 2, y: 4 },
  { n: 21, s: 'Sc', m: 'Scandium', g: 'Transition', x: 3, y: 4 },
  { n: 22, s: 'Ti', m: 'Titanium', g: 'Transition', x: 4, y: 4 },
  { n: 23, s: 'V', m: 'Vanadium', g: 'Transition', x: 5, y: 4 },
  { n: 24, s: 'Cr', m: 'Chromium', g: 'Transition', x: 6, y: 4 },
  { n: 25, s: 'Mn', m: 'Manganese', g: 'Transition', x: 7, y: 4 },
  { n: 26, s: 'Fe', m: 'Iron', g: 'Transition', x: 8, y: 4 },
  { n: 27, s: 'Co', m: 'Cobalt', g: 'Transition', x: 9, y: 4 },
  { n: 28, s: 'Ni', m: 'Nickel', g: 'Transition', x: 10, y: 4 },
  { n: 29, s: 'Cu', m: 'Copper', g: 'Transition', x: 11, y: 4 },
  { n: 30, s: 'Zn', m: 'Zinc', g: 'Post-transition', x: 12, y: 4 },
  { n: 31, s: 'Ga', m: 'Gallium', g: 'Post-transition', x: 13, y: 4 },
  { n: 32, s: 'Ge', m: 'Germanium', g: 'Metalloid', x: 14, y: 4 },
  { n: 33, s: 'As', m: 'Arsenic', g: 'Metalloid', x: 15, y: 4 },
  { n: 34, s: 'Se', m: 'Selenium', g: 'Non-metal', x: 16, y: 4 },
  { n: 35, s: 'Br', m: 'Bromine', g: 'Halogen', x: 17, y: 4 },
  { n: 36, s: 'Kr', m: 'Krypton', g: 'Noble Gas', x: 18, y: 4 },
  // Row 5
  { n: 37, s: 'Rb', m: 'Rubidium', g: 'Alkali Metal', x: 1, y: 5 },
  { n: 38, s: 'Sr', m: 'Strontium', g: 'Alkali Earth', x: 2, y: 5 },
  { n: 39, s: 'Y', m: 'Yttrium', g: 'Transition', x: 3, y: 5 },
  { n: 40, s: 'Zr', m: 'Zirconium', g: 'Transition', x: 4, y: 5 },
  { n: 41, s: 'Nb', m: 'Niobium', g: 'Transition', x: 5, y: 5 },
  { n: 42, s: 'Mo', m: 'Molybdenum', g: 'Transition', x: 6, y: 5 },
  { n: 43, s: 'Tc', m: 'Technetium', g: 'Transition', x: 7, y: 5 },
  { n: 44, s: 'Ru', m: 'Ruthenium', g: 'Transition', x: 8, y: 5 },
  { n: 45, s: 'Rh', m: 'Rhodium', g: 'Transition', x: 9, y: 5 },
  { n: 46, s: 'Pd', m: 'Palladium', g: 'Transition', x: 10, y: 5 },
  { n: 47, s: 'Ag', m: 'Silver', g: 'Transition', x: 11, y: 5 },
  { n: 48, s: 'Cd', m: 'Cadmium', g: 'Post-transition', x: 12, y: 5 },
  { n: 49, s: 'In', m: 'Indium', g: 'Post-transition', x: 13, y: 5 },
  { n: 50, s: 'Sn', m: 'Tin', g: 'Post-transition', x: 14, y: 5 },
  { n: 51, s: 'Sb', m: 'Antimony', g: 'Metalloid', x: 15, y: 5 },
  { n: 52, s: 'Te', m: 'Tellurium', g: 'Metalloid', x: 16, y: 5 },
  { n: 53, s: 'I', m: 'Iodine', g: 'Halogen', x: 17, y: 5 },
  { n: 54, s: 'Xe', m: 'Xenon', g: 'Noble Gas', x: 18, y: 5 },
  // Row 6
  { n: 55, s: 'Cs', m: 'Cesium', g: 'Alkali Metal', x: 1, y: 6 },
  { n: 56, s: 'Ba', m: 'Barium', g: 'Alkali Earth', x: 2, y: 6 },
  { n: 72, s: 'Hf', m: 'Hafnium', g: 'Transition', x: 4, y: 6 },
  { n: 73, s: 'Ta', m: 'Tantalum', g: 'Transition', x: 5, y: 6 },
  { n: 74, s: 'W', m: 'Tungsten', g: 'Transition', x: 6, y: 6 },
  { n: 75, s: 'Re', m: 'Rhenium', g: 'Transition', x: 7, y: 6 },
  { n: 76, s: 'Os', m: 'Osmium', g: 'Transition', x: 8, y: 6 },
  { n: 77, s: 'Ir', m: 'Iridium', g: 'Transition', x: 9, y: 6 },
  { n: 78, s: 'Pt', m: 'Platinum', g: 'Transition', x: 10, y: 6 },
  { n: 79, s: 'Au', m: 'Gold', g: 'Transition', x: 11, y: 6 },
  { n: 80, s: 'Hg', m: 'Mercury', g: 'Post-transition', x: 12, y: 6 },
  { n: 81, s: 'Tl', m: 'Thallium', g: 'Post-transition', x: 13, y: 6 },
  { n: 82, s: 'Pb', m: 'Lead', g: 'Post-transition', x: 14, y: 6 },
  { n: 83, s: 'Bi', m: 'Bismuth', g: 'Post-transition', x: 15, y: 6 },
  { n: 84, s: 'Po', m: 'Polonium', g: 'Post-transition', x: 16, y: 6 },
  { n: 85, s: 'At', m: 'Astatine', g: 'Halogen', x: 17, y: 6 },
  { n: 86, s: 'Rn', m: 'Radon', g: 'Noble Gas', x: 18, y: 6 },
  // Row 7
  { n: 87, s: 'Fr', m: 'Francium', g: 'Alkali Metal', x: 1, y: 7 },
  { n: 88, s: 'Ra', m: 'Radium', g: 'Alkali Earth', x: 2, y: 7 },
  { n: 104, s: 'Rf', m: 'Rutherfordium', g: 'Transition', x: 4, y: 7 },
  { n: 105, s: 'Db', m: 'Dubnium', g: 'Transition', x: 5, y: 7 },
  { n: 106, s: 'Sg', m: 'Seaborgium', g: 'Transition', x: 6, y: 7 },
  { n: 107, s: 'Bh', m: 'Bohrium', g: 'Transition', x: 7, y: 7 },
  { n: 108, s: 'Hs', m: 'Hassium', g: 'Transition', x: 8, y: 7 },
  { n: 109, s: 'Mt', m: 'Meitnerium', g: 'Transition', x: 9, y: 7 },
  { n: 110, s: 'Ds', m: 'Darmstadtium', g: 'Transition', x: 10, y: 7 },
  { n: 111, s: 'Rg', m: 'Roentgenium', g: 'Transition', x: 11, y: 7 },
  { n: 112, s: 'Cn', m: 'Copernicium', g: 'Post-transition', x: 12, y: 7 },
  { n: 113, s: 'Nh', m: 'Nihonium', g: 'Post-transition', x: 13, y: 7 },
  { n: 114, s: 'Fl', m: 'Flerovium', g: 'Post-transition', x: 14, y: 7 },
  { n: 115, s: 'Mc', m: 'Moscovium', g: 'Post-transition', x: 15, y: 7 },
  { n: 116, s: 'Lv', m: 'Livermorium', g: 'Post-transition', x: 16, y: 7 },
  { n: 117, s: 'Ts', m: 'Tennessine', g: 'Halogen', x: 17, y: 7 },
  { n: 118, s: 'Og', m: 'Oganesson', g: 'Noble Gas', x: 18, y: 7 },
  // Lanthanides (y=8 for offset)
  { n: 57, s: 'La', m: 'Lanthanum', g: 'Lanthanide', x: 4, y: 8 },
  { n: 58, s: 'Ce', m: 'Cerium', g: 'Lanthanide', x: 5, y: 8 },
  { n: 59, s: 'Pr', m: 'Praseodymium', g: 'Lanthanide', x: 6, y: 8 },
  { n: 60, s: 'Nd', m: 'Neodymium', g: 'Lanthanide', x: 7, y: 8 },
  { n: 61, s: 'Pm', m: 'Promethium', g: 'Lanthanide', x: 8, y: 8 },
  { n: 62, s: 'Sm', m: 'Samarium', g: 'Lanthanide', x: 9, y: 8 },
  { n: 63, s: 'Eu', m: 'Europium', g: 'Lanthanide', x: 10, y: 8 },
  { n: 64, s: 'Gd', m: 'Gadolinium', g: 'Lanthanide', x: 11, y: 8 },
  { n: 65, s: 'Tb', m: 'Terbium', g: 'Lanthanide', x: 12, y: 8 },
  { n: 66, s: 'Dy', m: 'Dysprosium', g: 'Lanthanide', x: 13, y: 8 },
  { n: 67, s: 'Ho', m: 'Holmium', g: 'Lanthanide', x: 14, y: 8 },
  { n: 68, s: 'Er', m: 'Erbium', g: 'Lanthanide', x: 15, y: 8 },
  { n: 69, s: 'Tm', m: 'Thulium', g: 'Lanthanide', x: 16, y: 8 },
  { n: 70, s: 'Yb', m: 'Ytterbium', g: 'Lanthanide', x: 17, y: 8 },
  { n: 71, s: 'Lu', m: 'Lutetium', g: 'Lanthanide', x: 18, y: 8 },
  // Actinides (y=9 for offset)
  { n: 89, s: 'Ac', m: 'Actinium', g: 'Actinide', x: 4, y: 9 },
  { n: 90, s: 'Th', m: 'Thorium', g: 'Actinide', x: 5, y: 9 },
  { n: 91, s: 'Pa', m: 'Protactinium', g: 'Actinide', x: 6, y: 9 },
  { n: 92, s: 'U', m: 'Uranium', g: 'Actinide', x: 7, y: 9 },
  { n: 93, s: 'Np', m: 'Neptunium', g: 'Actinide', x: 8, y: 9 },
  { n: 94, s: 'Pu', m: 'Plutonium', g: 'Actinide', x: 9, y: 9 },
  { n: 95, s: 'Am', m: 'Americium', g: 'Actinide', x: 10, y: 9 },
  { n: 96, s: 'Cm', m: 'Curium', g: 'Actinide', x: 11, y: 9 },
  { n: 97, s: 'Bk', m: 'Berkelium', g: 'Actinide', x: 12, y: 9 },
  { n: 98, s: 'Cf', m: 'Californium', g: 'Actinide', x: 13, y: 9 },
  { n: 99, s: 'Es', m: 'Einsteinium', g: 'Actinide', x: 14, y: 9 },
  { n: 100, s: 'Fm', m: 'Fermium', g: 'Actinide', x: 15, y: 9 },
  { n: 101, s: 'Md', m: 'Mendelevium', g: 'Actinide', x: 16, y: 9 },
  { n: 102, s: 'No', m: 'Nobelium', g: 'Actinide', x: 17, y: 9 },
  { n: 103, s: 'Lr', m: 'Lawrencium', g: 'Actinide', x: 18, y: 9 },
];

export const PLANT_PROPERTIES = {
  'Aloe Vera': { reducingPower: 0.8, baseSize: 25, efficiency: 0.85 },
  'Neem': { reducingPower: 0.7, baseSize: 30, efficiency: 0.75 },
  'Green Tea': { reducingPower: 0.95, baseSize: 15, efficiency: 0.92 },
  'Tulsi': { reducingPower: 0.75, baseSize: 28, efficiency: 0.80 },
  'Citrus Peel': { reducingPower: 0.85, baseSize: 20, efficiency: 0.88 },
  'Moringa': { reducingPower: 0.82, baseSize: 22, efficiency: 0.86 },
  'Hibiscus': { reducingPower: 0.78, baseSize: 26, efficiency: 0.82 },
  'Papaya': { reducingPower: 0.72, baseSize: 32, efficiency: 0.78 },
  'Ginger': { reducingPower: 0.88, baseSize: 18, efficiency: 0.90 },
  'Garlic': { reducingPower: 0.84, baseSize: 24, efficiency: 0.84 },
  'Turmeric': { reducingPower: 0.92, baseSize: 12, efficiency: 0.94 },
  'Eucalyptus': { reducingPower: 0.80, baseSize: 30, efficiency: 0.85 },
  'Cinnamon': { reducingPower: 0.90, baseSize: 14, efficiency: 0.91 },
  'Grape Seed': { reducingPower: 0.94, baseSize: 10, efficiency: 0.96 },
  'Onion Peel': { reducingPower: 0.76, baseSize: 28, efficiency: 0.81 },
  'Orange Peel': { reducingPower: 0.86, baseSize: 19, efficiency: 0.89 },
  'Lavender': { reducingPower: 0.74, baseSize: 31, efficiency: 0.79 },
  'Rosemary': { reducingPower: 0.77, baseSize: 29, efficiency: 0.82 },
  'Cactus': { reducingPower: 0.68, baseSize: 35, efficiency: 0.72 },
  'Bamboo': { reducingPower: 0.65, baseSize: 40, efficiency: 0.70 },
  'Rose': { reducingPower: 0.71, baseSize: 28, efficiency: 0.79 },
  'Jasmine': { reducingPower: 0.69, baseSize: 32, efficiency: 0.76 },
  'Peppermint': { reducingPower: 0.82, baseSize: 21, efficiency: 0.86 },
  'Basil': { reducingPower: 0.79, baseSize: 24, efficiency: 0.83 },
  'Thyme': { reducingPower: 0.81, baseSize: 22, efficiency: 0.85 },
  'Oregano': { reducingPower: 0.83, baseSize: 20, efficiency: 0.87 },
  'Cloves': { reducingPower: 0.91, baseSize: 13, efficiency: 0.93 },
  'Cardamom': { reducingPower: 0.76, baseSize: 27, efficiency: 0.81 },
  'Black Pepper': { reducingPower: 0.84, baseSize: 19, efficiency: 0.88 },
  'Coriander': { reducingPower: 0.73, baseSize: 30, efficiency: 0.78 },
  'Fennel': { reducingPower: 0.72, baseSize: 31, efficiency: 0.77 },
  'Cumin': { reducingPower: 0.75, baseSize: 28, efficiency: 0.80 },
  'Saffron': { reducingPower: 0.96, baseSize: 9, efficiency: 0.97 },
  'Vanilla': { reducingPower: 0.66, baseSize: 38, efficiency: 0.71 },
  'Coffee': { reducingPower: 0.89, baseSize: 16, efficiency: 0.91 },
  'Cocoa': { reducingPower: 0.87, baseSize: 18, efficiency: 0.89 },
  'Tea Tree': { reducingPower: 0.85, baseSize: 20, efficiency: 0.88 },
  'Lemon Balm': { reducingPower: 0.78, baseSize: 25, efficiency: 0.82 },
  'Ashwagandha': { reducingPower: 0.74, baseSize: 32, efficiency: 0.79 },
  'Ginseng': { reducingPower: 0.76, baseSize: 30, efficiency: 0.81 },
  'Ginkgo Biloba': { reducingPower: 0.80, baseSize: 24, efficiency: 0.84 },
  'Echinacea': { reducingPower: 0.75, baseSize: 28, efficiency: 0.80 },
  'Calendula': { reducingPower: 0.72, baseSize: 31, efficiency: 0.77 },
  'Chamomile': { reducingPower: 0.70, baseSize: 33, efficiency: 0.75 },
  'Strawberry': { reducingPower: 0.82, baseSize: 20, efficiency: 0.86 },
  'Blueberry': { reducingPower: 0.86, baseSize: 17, efficiency: 0.89 },
  'Raspberry': { reducingPower: 0.84, baseSize: 18, efficiency: 0.87 },
  'Blackberry': { reducingPower: 0.85, baseSize: 17, efficiency: 0.88 },
  'Pomegranate': { reducingPower: 0.93, baseSize: 11, efficiency: 0.95 },
  'Grapefruit': { reducingPower: 0.87, baseSize: 18, efficiency: 0.89 },
  'Lime': { reducingPower: 0.88, baseSize: 17, efficiency: 0.90 },
  'Spearmint': { reducingPower: 0.80, baseSize: 22, efficiency: 0.84 },
  'Lemon': { reducingPower: 0.89, baseSize: 16, efficiency: 0.91 },
  'Pineapple': { reducingPower: 0.79, baseSize: 24, efficiency: 0.82 },
  'Mango': { reducingPower: 0.77, baseSize: 26, efficiency: 0.81 },
  'Amla': { reducingPower: 0.93, baseSize: 11, efficiency: 0.94 },
  'Rhodiola rosea': { reducingPower: 0.88, baseSize: 15, efficiency: 0.90 },
  'Geranium': { reducingPower: 0.85, baseSize: 22, efficiency: 0.86 },
  'Magnolia': { reducingPower: 0.79, baseSize: 26, efficiency: 0.82 },
  'Stevia Leaf': { reducingPower: 0.91, baseSize: 14, efficiency: 0.92 },
  'Fenugreek': { reducingPower: 0.84, baseSize: 19, efficiency: 0.87 },
  'Papain': { reducingPower: 0.82, baseSize: 20, efficiency: 0.85 },
  'Quinine': { reducingPower: 0.80, baseSize: 23, efficiency: 0.83 },
  'Spirulina': { reducingPower: 0.92, baseSize: 10, efficiency: 0.95 },
  'Seaweed': { reducingPower: 0.87, baseSize: 18, efficiency: 0.89 },
  'Cinchona Bark': { reducingPower: 0.78, baseSize: 28, efficiency: 0.81 },
  'Lemon Grass': { reducingPower: 0.83, baseSize: 21, efficiency: 0.85 },
  'Siberian Nettle Root': { reducingPower: 0.72, baseSize: 31, efficiency: 0.78 },
  'Tribulus terrestris': { reducingPower: 0.86, baseSize: 18, efficiency: 0.89 },
  'Arnica Montana': { reducingPower: 0.79, baseSize: 25, efficiency: 0.84 },
  'Yohimbe Bark': { reducingPower: 0.81, baseSize: 22, efficiency: 0.85 },
  'Milk Thistle Seed': { reducingPower: 0.89, baseSize: 15, efficiency: 0.91 },
  'Marigold': { reducingPower: 0.80, baseSize: 25, efficiency: 0.84 },
  'Oak Bark': { reducingPower: 0.85, baseSize: 20, efficiency: 0.88 },
  'Pine Needle': { reducingPower: 0.77, baseSize: 32, efficiency: 0.80 },
  'Artichoke': { reducingPower: 0.75, baseSize: 34, efficiency: 0.79 },
  'Astragalus': { reducingPower: 0.81, baseSize: 24, efficiency: 0.84 },
  'Sea Buckthorn': { reducingPower: 0.90, baseSize: 12, efficiency: 0.92 },
  'Elderberry': { reducingPower: 0.88, baseSize: 15, efficiency: 0.90 },
  'Goji Berry': { reducingPower: 0.86, baseSize: 18, efficiency: 0.88 },
  'Dandelion': { reducingPower: 0.79, baseSize: 24, efficiency: 0.83 },
  'Matcha': { reducingPower: 0.97, baseSize: 8, efficiency: 0.98 },
};

export const PLANT_DESCRIPTIONS: Record<string, string> = {
  'Aloe Vera': 'Rich in aloesin and lignin, Aloe Vera provides excellent stabilization and produces moderate-sized particles with high biocompatibility.',
  'Neem': 'Contains azadirachtin which acts as an effective capping agent, resulting in stable, antimicrobial nanoparticles.',
  'Green Tea': 'High concentration of polyphenols and catechins enables rapid reduction and high-yield synthesis of small particles.',
  'Tulsi': 'Known for its high antioxidant capacity, it facilitates the formation of uniform spherical nanoparticles with potent bioactivity.',
  'Citrus Peel': 'Abundant in limonene and hesperidin, providing high reducing power and eco-friendly synthesis pathways.',
  'Moringa': 'Contains various proteins and vitamins that promote fast nucleation and prevent particle aggregation.',
  'Hibiscus': 'Rich in anthocyanins and organic acids, which assist in controlling morphology and particle size distribution.',
  'Papaya': 'The presence of papain enzymes assists in both the reduction of silver ions and subsequent stabilization.',
  'Ginger': 'Contains gingerol and shogaol, which are highly effective in producing narrow-sized nanoparticles at room temperature.',
  'Garlic': 'Allicin and other sulfur-containing compounds provide unique stabilizing properties and enhanced antimicrobial activity.',
  'Turmeric': 'Curcuminoids allow for the synthesis of extremely small nanoparticles with exceptional stability and medicinal properties.',
  'Eucalyptus': 'High cineole content facilitates rapid bio-reduction and creates a distinct aroma-stabilized nanoparticle complex.',
  'Cinnamon': 'Cinnamaldehyde acts as a powerful reducing agent, producing high-purity silver nanoparticles with rapid kinetics.',
  'Grape Seed': 'Proanthocyanidins offer one of the highest reducing potentials in nature, ideal for ultra-fine nanoparticle production.',
  'Onion Peel': 'The high quercetin content makes it a cost-effective and powerful source for biogenic silver synthesis.',
  'Orange Peel': 'Abundant citric acid and vitamin C content ensure high yield and monodispersity in the resulting suspension.',
  'Lavender': 'Terpenoids and linalool provide a gentle reduction process, resulting in highly stable, therapeutic-grade particles.',
  'Rosemary': 'Rosmarinic acid and carnosol provide balanced reduction and capping, suitable for agricultural applications.',
  'Cactus': 'Mucilage and organic acids provide a unique viscous environment for controlling large-scale growth of particles.',
  'Bamboo': 'Silica-rich extracts combined with flavonoids provide robust stabilization, creating durable nanoparticle structures.',
  'Rose': 'Rich in condensed tannins and gallic acid, rose petals facilitate a highly controlled synthesis for decorative and aesthetic nano-applications.',
  'Jasmine': 'Volatile oils and glycosides provide a distinct capping mechanism, resulting in stable and highly biocompatible spherical particles.',
  'Peppermint': 'Menthol and menthone act as powerful dual-action agents for rapid silver ion reduction and immediate surface stabilization.',
  'Basil': 'High phenolic content and essential oils like eugenol contribute to the formation of small, monodisperse nanoparticles.',
  'Thyme': 'Thymol and carvacrol provide exceptional antimicrobial properties to the synthesized nanoparticles, ideal for clinical coatings.',
  'Oregano': 'One of the highest antioxidant capacities in herbs, ensuring rapid reduction and high colloidal stability over long periods.',
  'Cloves': 'Eugenol concentration is extremely high, allowing for record-speed reduction and the creation of very small, bioactive silver clusters.',
  'Cardamom': 'Terpenes and esters facilitate a unique nucleation pattern, producing nanoparticles with high aspect ratios.',
  'Black Pepper': 'Piperine assists in the reduction and stabilization, creating nanoparticles with unique penetration capabilities for drug delivery.',
  'Coriander': 'Linalool-rich extract provides a gentle environment for synthesis, yielding uniform and non-toxic silver particles.',
  'Fennel': 'Anethole and other phytochemicals provide excellent stabilizing power, essential for food-grade packaging materials.',
  'Cumin': 'Cuminaldehyde acts as a strong reducing agent, effective for synthesizing crystalline nanoparticles at ambient conditions.',
  'Saffron': 'Crocin and safranal provide elite reducing power, enabling the synthesis of ultra-small nanoparticles with high medicinal value.',
  'Vanilla': 'Vanillin provides a slow, controlled reduction process, ideal for applications requiring extremely high uniformity in size.',
  'Coffee': 'Caffeine and chlorogenic acids facilitate very rapid reduction, producing a high concentration of nanoparticles in minutes.',
  'Cocoa': 'Theobromine and polyphenols act as excellent capping agents, creating a protective shell around particles for enhanced shelf-life.',
  'Tea Tree': 'Terpinen-4-ol provides natural antiseptic properties that are carried over to the silver particles, creating dual-action antimicrobials.',
  'Lemon Balm': 'Rosmarinic acid content ensures high yield and excellent dispersion of particles in aqueous solutions.',
  'Ashwagandha': 'Withanolides provide a biological template for particle growth, resulting in unique bio-functionalized nanoparticle surfaces.',
  'Ginseng': 'Ginsenosides act as effective bio-templates, guiding the synthesis towards specific octahedral and decahedral shapes.',
  'Ginkgo Biloba': 'Flavone glycosides provide superior stabilization, making these particles ideal for neurological imaging research.',
  'Echinacea': 'Polysaccharides and glycoproteins assist in producing nanoparticles with modified immune-response properties.',
  'Calendula': 'Carotenoids and saponins provide a soft capping layer, ensuring high biocompatibility for dermatological applications.',
  'Chamomile': 'Apigenin and bisabolol facilitate a calm, steady synthesis of highly stable and non-clumping silver suspensions.',
  'Strawberry': 'Ellagic acid and Vitamin C ensure high purity and rapid formation of spherical nanoparticles with a fruit-derived shell.',
  'Blueberry': 'Anthocyanins provide excellent electron-transfer capabilities for rapid reduction and high-yield synthesis.',
  'Raspberry': 'Ketones and organic acids facilitate a robust reduction pathway, yielding highly stable and consistent particle sizes.',
  'Blackberry': 'High phenolic content provides a strong protective layer, preventing oxidation of the metallic silver core.',
  'Pomegranate': 'Punicalagins offer exceptional reducing potential, rivaling synthetic chemicals while maintaining absolute bio-safety.',
  'Grapefruit': 'Naringin and various flavonoids provide a high-efficiency pathway for green synthesis with excellent particle distribution.',
  'Lime': 'High acidity and vitamin C content ensure rapid kinetics and high dispersion stability in acidic environments.',
  'Spearmint': 'Carvone and limonene provide a specialized capping mechanism for producing particles with high surface energy.',
  'Lemon': 'Citric acid acts as both a reducing and stabilizing agent, producing classic high-performance biogenic nanoparticles.',
  'Pineapple': 'Bromelain enzymes assist in the break-down of precursors and stabilization of the resulting nano-suspension.',
  'Mango': 'Mangiferin provides a unique biological cap, resulting in nanoparticles with high antioxidant and anti-inflammatory activity.',
  'Amla': 'Extremely high in Vitamin C and gallic acid, Amla (Indian Gooseberry) provides superior reducing power for the rapid production of small, stable silver nanoparticles.',
  'Rhodiola rosea': 'Contains high levels of salidroside and rosavins, which facilitate controlled nucleation and offer unique bioactive capping for medical use.',
  'Geranium': 'Rich in citronellol and geraniol, providing rapid reduction and excellent antimicrobial synergy with metallic nanoparticles.',
  'Stevia Leaf': 'Characterized by high glycoside content, Stevia serves as a dual reducing and powerful capping agent for stable colloidal suspensions.',
  'Fenugreek': 'Rich in galactomannan and flavonoids, promoting the formation of highly stable and non-clumping nanoparticles.',
  'Papain': 'Proteolytic enzymes in Papain assist in breaking down metal precursors and providing a robust protective protein shell.',
  'Spirulina': 'A protein-dense blue-green algae extract that provides elite bio-stabilization and imparts a bio-functionalized surface to nanoparticles.',
  'Seaweed': 'Abundant in alginates and minerals, facilitating the synthesis of crystalline nanoparticles with enhanced catalytic properties.',
  'Siberian Nettle Root': 'Rich in scopoletin and lignans, offering specialized phytochemical profiles for biogenic synthesis of bioactive nanoparticles.',
  'Tribulus terrestris': 'Contains steroidal saponins and flavonoids that act as powerful biological templates for controlling nanoparticle size and shape.',
  'Arnica Montana': 'Abundant in sesquiterpene lactones and phenolic acids, which assist in rapid bio-reduction and high-density stabilization.',
  'Yohimbe Bark': 'Rich in yohimbine and secondary alkaloids that provide a unique stabilizing environment for high-purity metallic particles.',
  'Quinine': 'An alkaloid-rich extract that provides a rigid molecular framework for the formation of extremely uniform and stable metallic clusters.',
  'Cinchona Bark': 'High quinine and quinidine content facilitate a unique nucleation-growth mechanism for specialized catalytic particles.',
  'Magnolia': 'Contains magnolol and honokiol, which provide powerful antioxidant shielding and excellent surface stabilization.',
  'Sea Buckthorn': 'Rich in vitamins C, E and flavonoids, facilitating rapid nucleation and producing small, highly stable nanoparticles.',
  'Elderberry': 'Abundant in anthocyanins which act as powerful reducing agents and provide a distinct bio-capping layer.',
  'Goji Berry': 'Contains complex polysaccharides and carotenoids that guide controlled particle growth and enhance biocompatibility.',
  'Dandelion': 'Rich in luteolin and other polyphenols, providing a steady reduction rate and uniform spherical morphology.',
  'Matcha': 'Concentrated catechins and L-theanine provide elite-level reducing power and immediate surface passivations for ultra-fine nanoparticles.',
};

export const EDUCATIONAL_CONTENT = {
  whatIsIt: "Green synthesis of metallic nanoparticles is an eco-friendly approach that uses biological entities like plant extracts, fungi, or bacteria as reducing and stabilizing agents instead of hazardous chemicals. Various metals like Silver (Ag), Gold (Au), and Copper (Cu) can be synthesized using this 'Green Engine' approach.",
  howItWorks: "1. Extraction: Phytochemicals are extracted from plants. 2. Reduction: Metal ions are reduced to metallic atoms (e.g., Ag+ to Ag0 or Au3+ to Au0). 3. Nucleation: Metallic atoms cluster to form stable nuclei. 4. Growth & Stabilization: Nuclei grow into nanoparticles, stabilized by plant biomolecules.",
  applications: [
    "Silver: Potent antimicrobial agents",
    "Gold: Targeted drug delivery & bio-imaging",
    "Copper: High-efficiency industrial catalysis",
    "Platinum/Palladium: Hydrogen fuel cell catalysts",
    "Iron/Zinc: Environmental remediation & optics"
  ],
  conclusion: "The transition from synthetic chemical reduction to biogenic metallic synthesis represents a paradigm shift in nanotechnology. By selecting specific botanical extracts and metallic precursors from the periodic table, we can engineer nanoparticles with precisely tuned LSPR peaks, catalytic surface areas, and biocompatibility profiles for the next generation of nanomedicine."
};
